name: openim_enterprise_chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  shared_preferences: ^2.0.13
  path_provider: ^2.0.11
  sprintf: ^7.0.0
  rxdart: ^0.27.3
  pin_code_fields: ^7.3.0
  image_picker: ^0.8.4+9
  dio: ^4.0.4
  azlistview: ^2.0.0
  lpinyin: ^2.0.3
  country_code_picker: ^2.0.2
  image_gallery_saver: ^1.7.1
  flutter_easyloading: ^3.0.5
  wechat_assets_picker: ^7.3.1
  wechat_camera_picker: ^3.2.0+1
  file_picker: ^5.2.2
  open_filex: ^4.3.1
  permission_handler: ^10.1.0
  mime_type: ^1.0.0
  uuid: ^3.0.5
  cached_network_image: ^3.2.1
  lottie: ^1.2.2
  qr_flutter: ^4.0.0
  image_cropper: ^2.0.3
  dotted_decoration: ^2.0.0
  package_info_plus: ^1.3.1
  search_keyword_text: ^0.0.2
  qr_code_scanner: ^1.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  logger: ^1.1.0
  animated_text_kit: ^4.2.1
  flutter_local_notifications: 9.3.2
  flutter_app_badger: ^1.3.0
  crypto: ^3.0.1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.20
  sp_util: ^2.0.3
  common_utils: ^2.1.0
  uri_to_file: ^0.2.0
  map_launcher: ^2.2.1+1
  flutter_map: ^0.14.0
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2
  flutter_image_compress: ^1.1.0
  app_installer: ^1.1.0
  r_scan: ^0.1.6+1
  collection: ^1.15.0
  flutter_bugly: ^0.4.4
  flutter_cupertino_datetime_picker: ^3.0.0
  tencent_cos: ^1.0.5
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  syncfusion_flutter_sliders: ^19.4.55
  syncfusion_flutter_core: ^19.4.55
  font_awesome_flutter: ^10.0.0
  dart_date: ^1.1.1
  video_compress: ^3.1.1
  just_audio: ^0.9.30
  flutter_inappwebview: ^5.4.3+7
  vibration: ^1.7.5
  getuiflut: ^0.2.14
  scroll_to_index: ^3.0.1
  flutter_screen_lock: ^8.0.0
  local_auth: ^2.1.2
  gesture_password_widget: ^2.0.0
  flutter_openim_widget:
    path: flutter_openim_widget
  flutter_openim_live:
    path: flutter_openim_live
  flutter_openim_live_alert:
    git:
      url: 'https://github.com/hrxiang/flutter_openim_live_alert.git'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.10+1
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

dependency_overrides:
  scrollable_positioned_list: ^0.3.2
  device_info_plus: 7.0.1
  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh
      ref: master
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anim/
    - assets/audio/
    - assets/launcher_icon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
